### ISSUE TITLE
Piping and routes

### ISSUE THREAD

**Issue by spiffyjr** [zendframework/zend-stratigility#10]
I was having issues using my router as middleware off of Stratigility. Given the following code:

```php
$router = ...
$router->get('/', $handler1);

$router2 = ...
$router2->get('/', $handler2);
$router2->get('', $handler3);

$app->pipe($router);
$app->pipe('/articles', $router2);
```

You would expect `/` to match the first `handler1` and `/articles` to match `handler2`. This is not the case, however, as `/articles` will match `handler3` instead. I think there's a leading slash being removed somewhere but I haven't had time to debug it yet.

This is a fairly critical bug since you won't be able to take a set of routes and move them from one pipe() to another and have them work identical unless you have an optional leading slash in your route or duplicate the route entirely.

**Comment by weierophinney** [comment]
When reading your code, I'd expect the following:

- `$handler1` will always be executed. (`/` and empty path indicate handlers that should be executed on every request.)
- `$handler2` and `$handler3` will be *both* be executed when the path is `/articles` *or* `/articles/` (trailing slash).

Essentially, an empty path and path with only a slash are considered equivalent internally in Stratigility; we even have tests for this behavior (I termed them "root paths", and test for them in `testMiddlewareTreatsBothSlashAndEmptyPathAsTheRootPath()` and `testNestedMiddlewareMatchesOnlyAtPathBoundaries()`). The only way they are treated differently is with regards to how the request's URI path is returned (if the trailing `/` is present, it's represented) when you're in the executed middleware.

Knowing that information… does that suggest a path forward?

**Comment by spiffyjr** [comment]
I'll dig into this a bit more but I suspect the trailing slash not being kept is the issue. e.g., `$request->getUri()-.getPath() == '/'` even for http://127.0.0.1 but for http://127.0.0.1/articles `$request->getUri()-.getPath() == ''`.

I think the trailing slash should be present so routers can handle them identically.

**Comment by weierophinney** [comment]
> I think the trailing slash should be present so routers can handle them identically.

I've had ping-ponging pull requests on this very subject, with everyone able to make excellent cases for why the behavior they prefer should be used. I've chosen the current implementation because it reflects how the route was invoked by the client (which means you can create a "self" URI that's identical to how it was invoked).

Technically, however, RFC 3986 indicates that `/` should only be used as a resource separator on the path; i.e., `/articles` and `/articles/` should behave identically. In practice, though, they may not, as the most popular web server (*cough*apache*cough*) will treat the first as a request for a file, and fail to match if it does not exist, but treat the second as a directory, and match if there's an index file present below the directory. In other words, it treats the URI path as equivalent to a filesystem path; RFC 3986 does not stipulate *at all* that it needs to be a filesystem path.

I'm not sure what to do at this point, because the standards and implementations differ on whether or not presence of a trailing slash is equivalent to lack of one. The easiest course right now is to make no change, but if you can gather enough evidence from your own usage **and** from others that making the change makes sense, I'll consider it.

**Comment by spiffyjr** [comment]
I just look at it with respect to $_SERVER['PATH'] since reusable middleware can only make assumptions about what that will have. Look at other implementations like node. How does it handle middleware? I can only assume that it can be piped/used at any endpoint and behave identically without changing the routing.

**Comment by weierophinney** [comment]
Node doesn't provide middleware. Packages for node, such as Connect, Express, Hapi, and others, provide middleware. Stratigility ports Connect, and, interestingly, Connect has some very similar issues. In both cases, however, given the following:

```php
$articles = new MiddlewarePipe();
$articles->pipe(function ($req, $res, $next) {
    if (strlen($req->getUri()->getPath()) > 1) {
        // we have a non-root path
        return;
    }
});
$app->pipe('/articles', $articles);
```

`$articles` will be invoked for either `/articles` or `/articles/`. In fact, it will be invoked even for `/articles/foo`, which is why I added that conditional. If you have middleware that matches at the root, you *must* check for a subpath when using Connect or Stratigility, because middleware that matches at the root is executed for *any* match.

So, my point is that we should document the above conditional as the way to check if there is a non-root path when inside a middleware that executes on the root path and which should only execute if the root path is matched. Does that make sense, @spiffyjr ?

**Comment by spiffyjr** [comment]
Sorry, I meant Express not Node. Documenting that makes sense and would be quite helpful.

**Comment by weierophinney** [comment]
@spiffyjr I've altered the docs slightly to demonstrate testing for the root path:

- https://github.com/zendframework/zend-stratigility/blob/master/doc/book/middleware.md

(first example)

Do you think I should call it out more?

**Comment by spiffyjr** [comment]
No, I think that's sufficient. Thanks for the update.
