### ISSUE TITLE
Getting paths from pipeline

### ISSUE THREAD

**Issue by kynx** [zendframework/zend-stratigility#101]
I would like to be able to get a list of the paths that have been added to my `MiddlewarePipe`. My use case is this:

I am migrating an application to zend-expressive that includes several distinct sub-applications at different paths (say '/admin' and '/soap'), some of which require routing, some which don't. There is also a white label sub-application that administrators can brand and expose to their customers via a top-level path they define (ie '/mycustomer'). I need to ensure that the path they enter is not part of the core pipeline.

While I could just hard-code a list of paths it would be better if I could access something like `$app->getPipedPaths()` right after the programatic pipeline has been built. Not 100% sure if this belongs in Stratigility or Expressive - would this be of interest here?

**Comment by xtreamwayz** [comment]
If you use expressive then zend-expressive would be the place to open the issue. Fortunately since Expressive 2 (released yesterday), there is [Application::getRoutes()](https://github.com/zendframework/zend-expressive/blob/2.0.0/src/Application.php#L329-L337). That might be what you are looking for.

**Comment by weierophinney** [comment]
Closed, per reason stated in #103.
