### ISSUE TITLE
PSR-7 violations

### ISSUE THREAD

**Issue by mindplay-dk** [zendframework/zend-stratigility#24]
I just spent two hours trying to find out why a middleware was unable to set a header, and it turns out [this](https://github.com/zendframework/zend-stratigility/blob/master/src/Http/Response.php#L147) line of code violates [this](https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L124) clause of the spec:

> MUST return an instance that has the new and/or updated header and value.

The idea of a response being "complete" isn't even a thing in the spec.

Simply *ignoring* function calls in this manner makes it *very* hard to debug anything, and is extremely risky. If I called `setHeader()` (or any number of other methods) clearly I'm calling them for one reason, and one reason only - quietly ignoring this call is a clear violation of the spec.

Debugging this type of silent error is an absolute nightmare. Components and middleware worked perfectly in unit and integration tests, but then quietly failed when implemented in production code.

I'm baffled as to why you would think this feature is necessary in the first place? Request and Response models are already immutable - what possible reason could you have to disable an an already-immutable model instance from generating a new model?

If a given piece of middleware decides that a response is "complete", quite simply, it won't delegate control to the next middleware on the stack. Instead, this feature allows you to delegate control to the next middleware, but disabling it from actually doing anything - it will run, but can't actually *do* anything.

Am I crazy for thinking this is crazy??

**Comment by weierophinney** [comment]
@mindplay-dk I hate to be the tone police here, but yelling in frustration and insisting that a project is *wrong* and/or the authors are *crazy* is not a great way to collaborate. My first inclination is to delete this issue and ask you to cool off before reporting again.

I recognize that you are frustrated. However, I ask that you treat OSS authors with respect. Issues like this one are exactly the sort of issues that make developers pause before open sourcing their libraries, or quit altogether. Please be polite and civil in your feedback. This is your first warning.

---

The behavior or `$response->end()` is documented:

- https://github.com/zendframework/zend-stratigility/blob/master/doc/book/api.md#zendstratigilityhttpresponse

That section clearly states:

> Once `end()` has been called, the response is immutable.

The solution: do not call `end()`. (Which begs the question: if you feel the behavior is not part of the specification, *why did you call `end()` in the first place, considering it's not part of the PSR-7 response interface, but rather specific to Stratigility's decorator?*

---

The "complete" aspect is something ported from behavior in node.js and Sencha Connect, where a call to `response.end()` marks the response as complete so other middleware can no longer write to it; some middleware dispatchers in node.js look for responses marked complete in order to start streaming the response early, even while other middleware continues to execute. In other words, *in node*, it's a performance optimization.

I ported the functionality *because I was doing a port.* I tried to be feature complete.

I have, *several times in fact*, changed Stratigility in ways that deviate from Connect when I have noted architectural differences between node and PHP that don't make sense. One of those was changing the signature of `$next()` to *always* require the request and response instances; with immutable requests and responses, this was the only way we could communicate changed instances downstream.

I would definitely consider removing the end/complete functionality. Because PHP does not have the same runtime architecture as node.js, we cannot opportunistically emit the response in the same way that node.js can. That said, there *are* ways we could accomplish it, but these may not require having features like `end()` and its side effects.

If we do this, however, it's a BC break, and will require bumping to a new major version. I'd argue we should do the following:

- For a new minor version, mark `end()` and `isComplete()` as deprecated, and have them emit an `E_USER_DEPRECATED` error indicating they will be removed in the future.
- For the next major version, remove them.

I will definitely support such a pull request.

**Comment by mindplay-dk** [comment]
I apologize for my snarky tone, it's been a very long week, with very little to show for it, now more than a week behind schedule. Obviously that's no excuse and I should be trying to help instead of pointing fingers.

> Once `end()` has been called, the response is immutable.

How about:

> Once `end()` has been called, the response factory functions (functions named `with_()`) are disabled and cannot be used to create new response objects.

"Immutable" is confusing, both in the programming sense, and in the PSR-7 context - it doesn't normally mean that methods stop working, it generally means the interface of the class is such that it's internal state cannot be manipulated.

I have very little experience with Node, but I don't recall it working that way in Connect either? As I recall, attempting to write to any stream after it has been closed, results in an error?

Is there a meaningful use-case for actually running middleware after the response object has been disabled? It can't modify the response at that point, and modifying the request could only lead to more confusion, as those changes cannot have any effect on the response at any later point in the stack, isn't that right?

I think the proper thing would be to throw an exception, which would have been easy to debug - an exception would prompt you to figure out the correct place to break the middleware chain, so you don't delegate to middleware components after these have been disabled from actually doing any work.

Or are we concerned about middleware that has side-effects not related to request/response?

(I'm asking, not trying to be facetious - I'm trying to help.)

**Comment by codeliner** [comment]
@mindplay-dk 

> Or are we concerned about middleware that has side-effects not related to request/response?

:+1: for the question.

Reading your comment I first thought - there are a lot of use cases for doing some post processing -
but the question made me thinking: Would it be good idea to let a middleware send an email after response is sent to the client? Most of the "post processing use cases" I can think off (when not all) are not related to the request/response cycle but are good candidates to put them in a worker queue. So I tend to agree with your conclusion:

> I think the proper thing would be to throw an exception

**Comment by weierophinney** [comment]
> Is there a meaningful use-case for actually running middleware after the response object has been disabled? It can't modify the response at that point, and modifying the request could only lead to more confusion, as those changes cannot have any effect on the response at any later point in the stack, isn't that right?

Yes: logging, caching, response introspection (ala Zend Server's Z-Ray or Blackfire).

> Most of the "post processing use cases" I can think off (when not all) are not related to the request/response cycle but are good candidates to put them in a worker queue.

The above use cases *could* be done in a worker queue, but don't necessarily *need* to be. In some cases, doing them on the local machine is *required*.

> I think the proper thing would be to throw an exception

I'm of the mind to either remove the methods or throw an exception. Either is a BC break in current behavior, however.

Whomever would like to file a pull request to do either, please feel free! Do so against the develop branch, however.

**Comment by mindplay-dk** [comment]
>> Is there a meaningful use-case for actually running middleware after the response object has been disabled?

> Yes: logging, caching, response introspection

Are you saying you would put those last?

Because I would put those first, to make sure they're always run - middleware further down the stack may not run at all, it depends on whether all previous middleware calls `$next`, which, if (say) my router middleware completes the response (returns a complete document), I should not delegate to `$next`, because that could corrupt the body, or corrupt the whole response by adding inappropriate headers, etc.

So if I'm writing middleware that doesn't alter the request or response (like introspection or logging) I place them at the top to make sure they always run - inside them, I call `$next` first, which means the top middleware is actually the last middleware to get it's hands on the final request/response, regardless of how far down the stack that happens to originate.

Isn't that right?

**Comment by weierophinney** [comment]
@mindplay-dk That's *one* way to implement. However, with Stratigility, you're not limited to onion-style call chains; you can also build pipelines, and typically safely call `$next()` all the way through, as you pass both the request and response.

This means you could have something like:

```php
$app->pipe(new LogRequest());
$app->pipe(/*... */);
$app->pipe(new LogResponse());
```

and have the middleware in the middle call `$next()`, allowing later middleware to do something with the arguments, including, in this case, logging the final response. That was what I was getting at with my earlier comment; you can have not just an onion, outside -> inside <- outside style of execution, but also a workflow -> style -> execution pattern. Yes, you can absolutely architect as you suggest, *but that's not the only architecture Stratigility enables*.

My question remains: are you interested in contributing one of the suggested solutions? If not, I'll mark it as a "help wanted".

**Comment by mindplay-dk** [comment]
Sorry, no. We've to swapped out Stratigility for Relay, in part because of our error handling issues, in part because it just does more than we need. We will continue to use Diactoros, but all we really needed from this was a simple middleware dispatcher.

I think my rub with Stratigility is probably founded on the simple fact that I didn't understand the full scope of it, and I couldn't find any simpler alternative at the time. Relay is dead simple, it just happens to fit what we're doing - no library can be right for every situation, I guess.

**Comment by codeliner** [comment]
@weierophinney you can assign the issue to me. Will submit a PR for it next week. As already mentioned I favor the exception solution.  IMHO throwing an exception is not a BC break in this case but a bug fix ;) But that is your choice. I'm fine with both.

**Comment by weierophinney** [comment]
Thanks! Let's go with exceptions, then.
