### ISSUE TITLE
Why ErrorMiddlewareInterface?

### ISSUE THREAD

**Issue by mnapoli** [zendframework/zend-stratigility#27]
I am trying to understand the benefits of having a separate interface and concept for error handling. I read about half of #16 (very long discussion) and still not see it.

Here is how I implemented it in a pet project not based on stratigility (the list below represents a middleware stack/pipe):

- ErrorHandlingMiddleware
- Middleware1
- Middleware2
- ...

The `ErrorHandlingMiddleware` is basically this:

```php
class ErrorHandlingMiddleware
{
    public function __invoke(RequestInterface $request, ResponseInterface $response, $next)
    {
        try {
            return $next($request, $response);
        } catch (\Exception $e) {
            // Show a nice error page
            // ...
            return $response;
        }
    }
}
```

So why not go with this (simpler) solution for stratigility?

**Comment by codeliner** [comment]
@mnapoli you can find the answer in [this comment](https://github.com/zendframework/zend-expressive/pull/64#issuecomment-133186551) by @weierophinney

**Comment by mnapoli** [comment]
@codeliner thank you, I read the whole thread that took a while but was worth it ;)

The answer you linked to didn't provide actual use case. I'm not saying it's wrong, it's just that it didn't help me much see the advantages of a different signature. E.g.

> **If you wanted to invoke a later middleware that can handle errors**, you'd have to do something like adding the error to the request attributes, which becomes a convention-based approach, vs a contract-based approach.

I don't see a use case for that. If a middleware wants to handle specific exceptions, it can be piped right after `ErrorHandlingMiddleware` and catch exceptions, and return responses.

Or if a middleware wanted to know about an exception but not handle it (e.g. a logger), it could be piped after the first middleware and catch/rethrow the exception:

- ErrorHandlingMiddleware
- ExceptionLoggerMiddleware: catch, log and rethrow exceptions
- Middleware1
- ...

I think I'm just not seeing the use case that justifies the current architecture.

**Comment by codeliner** [comment]
yeah sorry, the comment was part of a topic not related to ErrorMiddlewareInterface. It would have been better to mention this :)

Unfortunately, I'm not an expert with middleware so I cannot give you better answer than the linked comment. I guess Mathew can explain it better.

However, I try to give you an answer because it also helps me to learn more about the middleware concept :)

With your suggestion it is only possible to build onion-style middleware. But zend-stratigility also supports stack or pipline style. 

> If you wanted to invoke a later middleware that can handle errors

So later middleware is really a middleware piped **after** the exception causing middleware.

Does it makes sense to you?

//cc @weierophinney

**Comment by mnapoli** [comment]
> So later middleware is really a middleware piped **after** the exception causing middleware.

Maybe I'm missing something obvious but I've only seen middlewares in an onion architecture. If I want to have some code "after the exception causing middleware" I would do this:

```php
function ($req, $res, $next)
{
    try {
        $next($req, $res);
    } catch (Exception $e) {
        // After exception in sub-middleware
    }
}
```

**Comment by codeliner** [comment]
see [the slides](http://2015.phpday.it/talk/pushing-boundaries-zend-framework-3-and-the-future/)

3 middleware styles:

- onion
- stack / pipeline
- lambda

**Comment by weierophinney** [comment]
@mnapoli Middleware doesn't have to be only in the onion architecture, as @codeliner notes; just because *you* haven't seen it doesn't mean it doesn't exist and/or is not useful.

[Sencha Connect](https://github.com/senchalabs/connect), and, by extension, [ExpressJS](http://expressjs.com) use a combination of stack and onion style middleware, and they are what Stratigility is based on (the README even mentions that Stratigility is a port of Connect to PHP!). Express is the go-to middleware stack in Node; as such, it's a well-known pattern for many developers, and well-tested.

Technically speaking, however, it's not a "stack", it's a queue, as execution uses a FIFO flow — which is why we've adopted the terminology "pipeline" and "piping" in this project.

In pipeline style middleware, you create a queue of middleware; each is executed until one returns a response, or the queue is exhausted. This approach means that your middleware does not have to be architected to compose any other middleware; it simply receives the pipeline (`$next`) and calls on it if it cannot return a response (or wants to delegate further handling to a later middleware). As such, execution looks like this:

```
-> middleware1 -> middleware2-> middleware3
```

Versus onion style:

```
-> middleware1 -> middleware2 -> middleware3 <- middleware2 <- middleware1
```

Pipeline style middleware does not obviate onion-style middleware; you often will mix the two. ExpressJS-based applications will do this to do things like:

- Start timer
- Authenticate the user
- Pull and validate data from the request
- Route -> check for cached response -> initialize templating -> execute routed middleware <- render template <- cache response
- Inject timing information

As you can see (hopefully; ascii art is not my forté), we have a linear flow that also encapsulates an onion flow. And I can finally present some reasons for the linear flow:

- If there are things you want to execute every time, they can be *piped* before or after the main middleware lifecycle. This is useful for things like initializing sessions, processing cookies, processing identity (or lack thereof), etc.
- Error handling.

So, why would I do error handling as part of a pipeline and not part of an onion?

Two reasons:

- exceptions are not the only way to indicate an error.
- to allow delegating errors to the _application_.

As an example, I could do the following:

```php
public function ($request, $response, $next)
{
    $result = $this->authentication->authenticate($request);
    if ($result->failed()) {
        return $next($request, $response->withStatus(401), 401);
    }

    // ...
}
```

In my application, I can then define an _error handler_ that looks for this.

```php
$app->pipe(function ($error, $request, $response, $next) use ($templates) {
    if (401 !== $error) {
        return $next($request, $response, $error);
    }

    return new HtmlResponse(
        $templates->render('user::login'),
        401
    );
});
```

Observations:

- will only be executed *if* an error actually occurs. In other words, there's a slight performance benefit, as error handlers are skipped when processing the pipeline.
- we can have *multiple* error handlers, handling *discrete* conditions; this allows a granular approach to error handling. This goes hand-in-hand with the above point; I don't have to wrap all my middleware in layers and layers of error handlers.
- we can have a fallback error handler (via the "final handler") for anything our discrete error handlers cannot process.

One way granularity comes in handy is when providing alternate error representations. As an example, you can have different error handlers that can produce different output based on content negotiation:

```php
public function ($error, $request, $response, $next)
{
    if (! $this->negotiator->matches('application/json', $request->getHeader('Accept')) {
        return $next($request, $response, $error);
    }
    
    // Build JSON error response ...
}
```

This keeps error handlers small and targetted — and easily re-usable and composable in other projects.

Now, by default, our dispatcher currently wraps all calls to middleware in a try/catch block; if an exception is caught, we pass it on as the `$error` argument to `$next()`. This is done so that we can handle errors gracefully; there's been some debate in the repo already about whether or not this should be the default behavior (somebody already mentioned #16), and I'm open to having a non-catching dispatcher, and the ability to choose which one to use for your runtime.

However, currently, *there's nothing preventing you from doing as you suggested in your original question*; that's certainly valid, *and works fine now*. However, because this middleware library is implementing a pipeline, one useful aspect of pipelines is that they give us the ability to do error handling in other ways as well. I personally have found the pattern implemented useful in a number of projects, as it allows me to cleanly separate error handling from my application, and have a fine-grained approach.
