### ISSUE TITLE
Router?

### ISSUE THREAD

**Issue by jpkleemans** [zendframework/zend-stratigility#55]
I was wondering why there is a router integrated in this package. Are there use cases where you would use it instead of a dedicated router(-middleware)? Or is it just for prototyping?

**Comment by weierophinney** [comment]
There isn't a router in this package. 

When piping middleware, Stratigility optionally allows you to provide a literal path that must match; the dispatcher skips the middleware if no match occurs. If it does, that matching segment is stripped from the uri when dispatching the middleware. The use case is to allow:

- segmenting middleware layers by path
- reuse of middleware pipelines between different applications, without requiring changes to internal routing

As an example, you could develop API middleware that contains it's own routing capabilities, and test it in a development sandbox. When ready, you could then compare it into a larger application stack, but segregate it under the path `/api`. Due to the way Stratigility works, any request that does not match that at the start of the path skills over the API middleware entirely; when it does match, it steroids into the middleware, and routing occurs as if that path segment did not exist. 

The points to note:

- it's literal matching *only* - anything dynamic requires dedicated routing middleware.
- on matches, it strips the match from the uri before executing the matched middleware. 

If you're interested in routing middleware, Expressive offers routing abstractions and integration.

**Comment by jpkleemans** [comment]
Thanks for your clear answer!
